"""recreate persona_profiles table

Revision ID: 07e767d45bda
Revises: 460c8bab426b
Create Date: 2025-07-22 23:32:58.775133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e767d45bda'
down_revision: Union[str, None] = '460c8bab426b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('persona_description', sa.String(), nullable=False),
    sa.Column('key_traits', sa.JSON(), nullable=True),
    sa.Column('lifestyle_summary', sa.String(), nullable=True),
    sa.Column('financial_tendencies', sa.String(), nullable=True),
    sa.Column('source_qloo_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_profiles')
    # ### end Alembic commands ###
