"""establish relationships with coversation id

Revision ID: 2382c5ae2107
Revises: a754d33d72cf
Create Date: 2025-05-26 22:39:44.470343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2382c5ae2107'
down_revision: Union[str, None] = 'a754d33d72cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_messages', 'ai_conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_messages', type_='foreignkey')
    # ### end Alembic commands ###
