"""add is_active and priority table in ai insights

Revision ID: 3ef57c84ce38
Revises: cebe9fd4ec6d
Create Date: 2025-06-01 01:40:21.488306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef57c84ce38'
down_revision: Union[str, None] = 'cebe9fd4ec6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('ai_insights', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_insights', 'priority')
    op.drop_column('ai_insights', 'is_active')
    # ### end Alembic commands ###
