"""update PersonaProfile table

Revision ID: 4849e3fcedff
Revises: 33ec84e13eb1
Create Date: 2025-07-22 23:23:58.456018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4849e3fcedff'
down_revision: Union[str, None] = '33ec84e13eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('persona_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('persona_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_qloo_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('persona_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('persona_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('persona_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
