"""add user relation to bank trasactions

Revision ID: 65cc58d64553
Revises: 3801901f89c5
Create Date: 2025-05-31 17:42:46.037712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cc58d64553'
down_revision: Union[str, None] = '3801901f89c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'bank_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'user_id')
    # ### end Alembic commands ###
