"""update relations 2

Revision ID: 7e6699738831
Revises: 1df9c5554567
Create Date: 2025-05-31 21:50:45.761382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6699738831'
down_revision: Union[str, None] = '1df9c5554567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bank_categories_name'), 'bank_categories', type_='unique')
    op.drop_constraint(op.f('fk_bank_transactions_category'), 'bank_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'bank_transactions', 'bank_categories', ['category_id'], ['id'])
    op.drop_constraint(op.f('fk_expenses_category'), 'expenses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_expenses_category'), 'expenses', 'bank_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bank_transactions_category'), 'bank_transactions', 'bank_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_bank_categories_name'), 'bank_categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
