"""Pdf extractions changes

Revision ID: 8e206cad3d6c
Revises: d7cdc8b0fb8d
Create Date: 2025-05-30 16:11:50.656440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e206cad3d6c'
down_revision: Union[str, None] = 'd7cdc8b0fb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bank_transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'account_id')
    # ### end Alembic commands ###
