"""add_cultural_profile_to_persona

Revision ID: 9e029bbeb95e
Revises: 07e767d45bda
Create Date: 2025-07-30 01:56:28.503134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e029bbeb95e'
down_revision: Union[str, None] = '07e767d45bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to existing persona_profiles table
    op.add_column('persona_profiles', sa.Column('cultural_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('persona_profiles', sa.Column('financial_advice_style', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the added columns
    op.drop_column('persona_profiles', 'financial_advice_style')
    op.drop_column('persona_profiles', 'cultural_profile')
    # ### end Alembic commands ###
