"""establish relationships with user

Revision ID: a754d33d72cf
Revises: e2d8e37c1018
Create Date: 2025-05-26 22:35:00.136497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a754d33d72cf'
down_revision: Union[str, None] = 'e2d8e37c1018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_insights', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'financial_goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'financial_goals', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'ai_insights', type_='foreignkey')
    op.drop_constraint(None, 'ai_conversations', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    # ### end Alembic commands ###
