"""update relations 8

Revision ID: cebe9fd4ec6d
Revises: 995643914b14
Create Date: 2025-05-31 22:20:43.154461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cebe9fd4ec6d'
down_revision: Union[str, None] = '995643914b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transaction_tags')
    op.drop_table('bank_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bank_tags_pkey'),
    sa.UniqueConstraint('name', name='bank_tags_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('bank_transaction_tags',
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['bank_tags.id'], name=op.f('bank_transaction_tags_tag_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], name=op.f('bank_transaction_tags_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('bank_transaction_tags_pkey'))
    )
    # ### end Alembic commands ###
