"""remove unnessesary models

Revision ID: d53a58f3a3f0
Revises: 8cf58df6eef0
Create Date: 2025-05-29 13:38:00.365446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'd53a58f3a3f0'
down_revision: Union[str, None] = '8cf58df6eef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get database inspector
    inspector = inspect(op.get_bind())
    
    # Check if tables exist before dropping
    if 'ai_messages' in inspector.get_table_names():
        op.drop_table('ai_messages')
    
    if 'ai_conversations' in inspector.get_table_names():
        op.drop_table('ai_conversations')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name='ai_messages_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_messages_pkey')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('conversation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_conversations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_conversations_pkey')
    )
    # ### end Alembic commands ###
