"""add relationship between transaction and expense

Revision ID: dfb07e39d74c
Revises: 3ef57c84ce38
Create Date: 2025-06-05 14:19:16.757895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb07e39d74c'
down_revision: Union[str, None] = '3ef57c84ce38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'bank_transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'transaction_id')
    # ### end Alembic commands ###
