"""setup relationships

Revision ID: fb627d3b5d6c
Revises: 2382c5ae2107
Create Date: 2025-05-26 22:44:06.322211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb627d3b5d6c'
down_revision: Union[str, None] = '2382c5ae2107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'transaction_tags', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_tags', type_='foreignkey')
    op.drop_constraint(None, 'transaction_tags', type_='foreignkey')
    # ### end Alembic commands ###
