name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  HEROKU_APP_NAME: savvy-apis

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Heroku Container Registry
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

    - name: Release Heroku app
      run: |
        curl -X PATCH https://api.heroku.com/apps/${{ env.HEROKU_APP_NAME }}/formation \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -d '{"updates":[{"type":"web","docker_image":"'$(docker inspect registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web --format={{.Id}})'"}]}'

  notify:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.build-and-deploy.result }}" == "success" ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi