name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Login to Heroku
        run: |
          echo "machine api.heroku.com
          login ${{ secrets.HEROKU_EMAIL }}
          password ${{ secrets.HEROKU_API_KEY }}
          " > ~/.netrc
          chmod 600 ~/.netrc

      - name: Create Heroku Remote
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Clean Git Repository
        run: |
          git clean -fdx
          git reset --hard

      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main --force 